# Generated by Django 5.1.4 on 2024-12-25 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_payment_paymentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={},
        ),
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='timestamp',
            new_name='payment_time',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
