services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - uzinfocom_rent_car_system_drf_network

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "4432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - uzinfocom_rent_car_system_drf_network

  redis:
    image: redis:latest
    networks:
      - uzinfocom_rent_car_system_drf_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A uzinfocom_rent_car_system_drf worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
        - uzinfocom_rent_car_system_drf_network
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:

networks:
    uzinfocom_rent_car_system_drf_network:
        driver: bridge