# Generated by Django 5.1.4 on 2024-12-25 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rentalmodel_status'),
        ('stations', '0002_alter_stationmodel_options'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='pickup_station',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='return_station',
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rentalmodel',
            index=models.Index(fields=['client', 'status'], name='rentals_ren_client__ebc2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalmodel',
            index=models.Index(fields=['car', 'status'], name='rentals_ren_car_id_9b8722_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalmodel',
            index=models.Index(fields=['start_date', 'end_date'], name='rentals_ren_start_d_206072_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalmodel',
            index=models.Index(fields=['status'], name='rentals_ren_status_fdc72b_idx'),
        ),
    ]
