# Generated by Django 5.1.4 on 2024-12-26 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_reservationmodel_pickup_station_and_more'),
        ('vehicles', '0002_alter_vehiclemodel_options_alter_vehiclemodel_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalmodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalmodel',
            name='total_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicles.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservationmodel',
            index=models.Index(fields=['client', 'car', 'status'], name='rentals_res_client__161532_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationmodel',
            index=models.Index(fields=['car', 'start_date', 'end_date'], name='rentals_res_car_id_018220_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationmodel',
            index=models.Index(fields=['status'], name='rentals_res_status_93d47d_idx'),
        ),
    ]
