# Generated by Django 5.1.4 on 2024-12-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationmodel',
            options={'ordering': ['is_active', '-created_at']},
        ),
    ]
