# Generated by Django 5.1.4 on 2024-12-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stationmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='stationmodel',
            index=models.Index(fields=['name'], name='stations_st_name_fe7555_idx'),
        ),
        migrations.AddIndex(
            model_name='stationmodel',
            index=models.Index(fields=['is_active'], name='stations_st_is_acti_911fec_idx'),
        ),
        migrations.AddIndex(
            model_name='stationmodel',
            index=models.Index(fields=['latitude', 'longitude'], name='stations_st_latitud_046b4f_idx'),
        ),
    ]
