# Generated by Django 5.1.4 on 2024-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stationmodel_options'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['brand', 'model']},
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('RT', 'Rented'), ('MN', 'Maintenance')], db_index=True, default='AV', max_length=2),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['status'], name='vehicles_ve_status_952daf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['brand'], name='vehicles_ve_brand_9d8788_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['current_station'], name='vehicles_ve_current_e30d0e_idx'),
        ),
    ]
